### ISSUE TITLE
Access to node-sass binaries

### ISSUE THREAD

**Issue by nschonni** [nodejitsu/module-foundry#20]
The readme mentions that you're building node-sass on multiple platforms. Is it possible to get access to these releases? This is currently the hardest part about getting out a new release.

Currently, the binaries have been moved to https://github.com/andrew/node-sass-binaries to keep the main repo size down. Ideally this would be able to push back changes during the CI builds if any of the native code was changed.

PS: feel free to PR the SmartOS binaries if you want them to work without a rebuild on npm install.

/cc @andrew

**Comment by indexzero** [comment]
@nschonni All that list of packages says is that `module-foundry` can build `node-sass` on Linux, SmartOS and Windows. We are not maintaining a set of prebuilt binary modules anywhere.

**Comment by springmeyer** [comment]
@nschonni - you might be interest in checking out https://github.com/springmeyer/node-pre-gyp.

**Comment by indexzero** [comment]
@springmeyer That's interesting, but you'd still have to have three machines (or VMs) to properly distribute `.node` binaries for them. Maintaining those machines is the biggest problem.

**Comment by springmeyer** [comment]
@indexzero yes. In my case I automate builds for OSX and Linux using travis.ci. It is nothing special, but works. Here is an example for [node-sqlite3](https://github.com/mapbox/node-sqlite3/blob/node-pre-gyp/.travis.yml). For windows I'm currently maintaining builds manually on a local VM, but there are [indications travis will also provide Windows support](https://github.com/travis-ci/travis-ci/issues/216#issuecomment-24499219). So I'm hopeful I might eventually have 3 platforms covered with travis.
